name: Update Rider List
on:
  schedule:
    - cron: '0 8 * * 1' # Every Monday at 8am
  workflow_dispatch: # Allows you to run it manually with one click

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: pip install requests beautifulsoup4
      - name: Run scraper
        run: python update_riders.py
      - name: Commit and push changes
        run: |
          git config --global user.name 'RiderBot'
          git config --global user.email 'bot@github.com'
          git add riders.json
          git commit -m "Automated Rider Update" || exit 0
          git push
